phraseapp:
  access_token: "4f3e4a1b7e7c0f88604c93a2b3fef84c31746a8c8854ed491146d8962e0cc4f0"
  project_id: "4eda630a8c09a0bed2765af8978b4d0e"
  push:
    sources:
    - file: "./enrichment-admin/src/main/resources/fi/post/daas/registers/enrichment/web/*.<locale_code>.properties"
      params:
        file_format: "properties"
  pull:
    targets:
    - file: "./enrichment-admin/src/main/resources/fi/post/daas/registers/enrichment/web/.<locale_code>.properties"
      params:
        file_format: "properties"
